2011-Scorpio/Capstone

- client/components/navbar.js
- public/style.css
Stripped down navbar component
> edit: navbar

- client/components/Welcome.js
- client/routes.js
- client/store/spotify.js
- package-lock.json
- package.json
- server/api/spotify.js
> fix: spotify store

- client/components/Welcome.js
- client/store/spotify.js
- server/api/spotify.js
- server/auth/spotify.js
- server/db/models/user.js
> Spotifyoauthuser

- script/seed.js
- server/db/models/index.js
- server/db/models/playlist.js
Added playlist sequelize model with playlist ID and user ID
> Added Playlists Sequelize Model

- server/api/users.js
Added backend spotify api to fetch a song
> Added API route in backend to fetch a song from spotify

- server/auth/spotify.js
> updated oauth flow to update access token every login

- client/components/Welcome.js
- client/store/getRandom.js
- client/store/spotify.js
- server/auth/spotify.js
> Spotfyapiimprovements

- client/store/getRandom.js
- client/store/spotify.js
> tweaked random search algorithm

- client/components/PlayerPage.js
- client/components/navbar.js
- client/store/spotify.js
- public/style.scss
Refactored PlayerPage to class component. See commits for more info.
> Playerpage update

- client/components/LandingPage.js
- client/components/PlayerPage.js
- client/components/navbar.js
- client/routes.js
- public/style.scss
> Load random playlist

- client/components/LandingPage.js
- client/store/index.js
- client/store/userPlaylist.js
> Userplaylist

- client/components/PlayerPage.js
- client/store/userPlaylist.js
> feature: add current song to a user's spotify playlist

- client/components/AllPlaylists.js
- client/components/SinglePlaylist.js
- client/routes.js
- client/store/allPlaylists.js
- client/store/index.js
- client/store/singlePlaylist.js
> All playlists

- package.json
- script/deploy
- script/encrypt-heroku-auth-token.js
- server/db/db.js
Deployment still not working, trying to to see if main merge will fix issues
> add: db code from maddie

- server/auth/spotify.js
Added 'http://omakasemusic.herokuapp.com/auth/spotify/callback' to callback url on /auth/spotify route
> Added callback

- client/components/LandingPage.js
- client/components/PlayerPage.js
> added log-in ternary

- client/components/auth-form.js
> commented out log in form and changed log in with spotify into a button

- client/components/LandingPage.js
- client/components/PlayerPage.js
> Added links to the please log in text

- client/components/LandingPage.js
> changed choose playlist list to update dynamically with created playlist

- client/routes.js
delete single playlist reference in the routes component
> delete: single playlist comp

- client/routes.js
singlePlaylist route taken out of routes.js
> fix: singlePlaylist route

- server/auth/spotify.js
changed callback to process.env.SERVER_NAME and updated secrets to include localhost
> edit: secrets and server_name

- client/components/PlayerPage.js
- public/style.scss
added album art, ellipses to input that's too big, and style the component with padding and margins
> style: player page

- client/components/LandingPage.js
> fixed playlist list not updating on first click

- public/style.scss
> style: padding in player header

- client/components/NowPlaying.js
- client/components/PlayerPage.js
- client/components/navbar.js
- public/style.scss
> fix: now-playing

- client/components/RdrChart.js
> Radar chart

- client/components/LandingPage.js
- client/components/PlayerPage.js
- client/routes.js
- server/api/users.js
> Securityfixes

- client/store/charting.js
- client/store/spotify.js
- client/store/userPlaylist.js
> fixed token refresh issue

- client/components/AllPlaylists.js
- client/components/BackgroundShape.js
- client/components/Dashboard.js
- client/components/LandingPage.js
- client/components/RdrChart.js
- client/store/userPlaylist.js
- public/style.scss
> Landingpage

- client/store/spotify.js
> increased number of songs pulled from api to 40

- client/components/AllPlaylists.js
> added this.props.history.push(/explore)

- public/background.css
- public/index.html
- public/offline.html
- public/style.scss
Fixed the gradient border showing, improved the font load delay, and styled the offline page
> Friday fix

- client/components/About.js
- client/components/LandingPage.js
- public/index.html
- public/style.scss
added alt to images and changed footer formatting
> footer and accessibility

- client/components/Dashboard.js
- client/components/SinglePlaylist.js
> Chartforsingleplaylist
